services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gb
      POSTGRES_PASSWORD: gb
      POSTGRES_DB: gbsku
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gb -d gbsku"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://gb:gb@db:5432/gbsku
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:3000
      HOST: 0.0.0.0
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
