name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug lockfiles
        run: |
          echo "Repo root:"
          ls -la
          echo "backend/:"
          ls -la backend || true
          echo "frontend/:"
          ls -la frontend || true

      - name: Setup Node (cache backend lock)
        if: ${{ hashFiles('backend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Setup Node (cache root lock)
        if: ${{ hashFiles('package-lock.json') != '' && hashFiles('backend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup Node (no cache)
        if: ${{ hashFiles('backend/package-lock.json') == '' && hashFiles('package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Prisma generate
        working-directory: backend
        run: npx prisma generate

      - name: Lint
        working-directory: backend
        run: npm run lint --if-present

      - name: Unit tests + coverage
        working-directory: backend
        run: npm test -- --coverage --runInBand

      - name: E2E tests
        working-directory: backend
        run: npm run test:e2e -- --runInBand
