name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug lockfiles (backend)
        run: |
          ls -la
          ls -la backend || true

      - name: Setup Node (cache backend lock)
        if: ${{ hashFiles('backend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Setup Node (no cache)
        if: ${{ hashFiles('backend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Prisma generate
        working-directory: backend
        run: npx prisma generate

      - name: Lint
        working-directory: backend
        run: npm run lint --if-present

      - name: Unit tests + coverage
        working-directory: backend
        run: npm test -- --coverage --runInBand

      - name: E2E tests
        working-directory: backend
        run: npm run test:e2e -- --runInBand

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug lockfiles (frontend)
        run: |
          ls -la
          ls -la frontend || true

      - name: Setup Node (cache npm)
        if: ${{ hashFiles('frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Node (cache yarn)
        if: ${{ hashFiles('frontend/yarn.lock') != '' && hashFiles('frontend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Setup Node (no cache)
        if: ${{ hashFiles('frontend/package-lock.json') == '' && hashFiles('frontend/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (frontend)
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          else
            npm install
          fi

      - name: Lint (frontend)
        working-directory: frontend
        run: npm run lint --if-present

      - name: Tests (frontend)
        working-directory: frontend
        run: npm run test -- --coverage --runInBand --if-present

      - name: Build (frontend)
        working-directory: frontend
        run: npm run build --if-present
