name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install
        working-directory: backend
        run: npm ci

      - name: Prisma generate
        working-directory: backend
        run: npx prisma generate

      - name: Lint
        working-directory: backend
        run: npm run lint --if-present

      - name: Unit tests
        working-directory: backend
        run: npm test -- --coverage --runInBand

      - name: E2E tests
        working-directory: backend
        run: npm run test:e2e -- --runInBand

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        working-directory: frontend
        run: npm ci

      - name: Tests
        working-directory: frontend
        run: npm test -- --runInBand
